version: '3'
services:
  ghostblog:
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    depends_on:
      - "db"
    environment:
      database__client: mysql
      database__connection__host: db
      atabase__connection__database: ghost
      database__connection__user: root
      database__connection__password: lalala
    networks:
      - my-network
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lalala
    volumes:
      - ./data-base:/var/lib/mysql
    networks:
      - my-network
volumes:
  data-base:
networks:
  my-network: